Upgrade JaCoCo to 0.8.10
JaCoCo 0.8.7 supports class file versions only up to Java 17,
whereas JaCoCo 0.8.10 supports up to Java 20,
so after this change following messages won't appear in CI that uses Java 19

    java.lang.instrument.IllegalClassFormatException: Error while instrumenting javax/lang/model/SourceVersion.
        at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)
    ...
    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:196)
    ...

Seems that this was overlooked in
f7ea3edfde9f3247e0192df2a8813c1b4d1a991e